//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvdP.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrameworkMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TvdP.UnitTesting.Resources.FrameworkMessages", typeof(FrameworkMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected:&lt;{1}&gt;. Case is different for actual value:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreEqualCaseFailMsg {
            get {
                return ResourceManager.GetString("AreEqualCaseFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a difference no greater than &lt;{3}&gt; between expected value &lt;{1}&gt; and actual value &lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreEqualDeltaFailMsg {
            get {
                return ResourceManager.GetString("AreEqualDeltaFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected:&lt;{1} ({2})&gt;. Actual:&lt;{3} ({4})&gt;. {0}.
        /// </summary>
        internal static string AreEqualDifferentTypesFailMsg {
            get {
                return ResourceManager.GetString("AreEqualDifferentTypesFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected:&lt;{1}&gt;. Actual:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreEqualFailMsg {
            get {
                return ResourceManager.GetString("AreEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a difference greater than &lt;{3}&gt; between expected value &lt;{1}&gt; and actual value &lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreNotEqualDeltaFailMsg {
            get {
                return ResourceManager.GetString("AreNotEqualDeltaFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected any value except:&lt;{1}&gt;. Actual:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string AreNotEqualFailMsg {
            get {
                return ResourceManager.GetString("AreNotEqualFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not pass value types to AreSame(). Values converted to Object will never be the same. Consider using AreEqual(). {0}.
        /// </summary>
        internal static string AreSameGivenValues {
            get {
                return ResourceManager.GetString("AreSameGivenValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed. {1}.
        /// </summary>
        internal static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string Common_NullInMessages {
            get {
                return ResourceManager.GetString("Common_NullInMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (object).
        /// </summary>
        internal static string Common_ObjectString {
            get {
                return ResourceManager.GetString("Common_ObjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.Equals should not be used for Assertions. Please use Assert.AreEqual &amp; overloads instead..
        /// </summary>
        internal static string DoNotUseAssertEquals {
            get {
                return ResourceManager.GetString("DoNotUseAssertEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Expected type:&lt;{1}&gt;. Actual type:&lt;{2}&gt;..
        /// </summary>
        internal static string IsInstanceOfFailMsg {
            get {
                return ResourceManager.GetString("IsInstanceOfFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Type:&lt;{1}&gt;. Actual type:&lt;{2}&gt;. {0}.
        /// </summary>
        internal static string IsNotInstanceOfFailMsg {
            get {
                return ResourceManager.GetString("IsNotInstanceOfFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is invalid. The value cannot be null. {1}..
        /// </summary>
        internal static string NullParameterToAssert {
            get {
                return ResourceManager.GetString("NullParameterToAssert", resourceCulture);
            }
        }
    }
}
